### ISSUE TITLE
Python 3 Compatible

### ISSUE THREAD

**Issue by nickj21** [HdrHistogram/HdrHistogram_py#1]
Any chance this module will be made python 3 compatible?

**Comment by ahothan** [comment]
Maybe one day, just that I'm too busy right now with other work to do this and I do not really need python 3 either.
But looking forward for anybody to pick up this work.
Might not be that much work to do.

**Comment by nickj21** [comment]
No problem, I'll take a look.

**Comment by ahothan** [comment]
Closed with https://github.com/HdrHistogram/HdrHistogram_py/commit/129cb95eaf91282e840704a33692424cf8f84aa7
