### ISSUE TITLE
Include pure-python versions of encode/decode

### ISSUE THREAD

**Issue by Julian** [HdrHistogram/HdrHistogram_py#12]
https://github.com/HdrHistogram/HdrHistogram_py/blob/master/src/python-codec.c includes a comment that pure python versions are too slow, but on PyPy, they'd very likely be preferred, and faster.

**Comment by ahothan** [comment]
Julian, I had a pure python version of the codec, just need to dig it out from git history.
Reason I moved to C extensions is that python version was pretty slow, but perhaps with Pypy it will be good enough.
One possible hurdle is that the pure python codec only supported the V1 encoding (as the support for V2 happened around the time C was added), so might not be straightforward.

I'm really busy with other stuff so can't commit on when Pypy could be supported.
Perhaps somebody else can contribute.

**Comment by Julian** [comment]
Ah, awesome!

Definitely understood on being busy :)

I'm going to put some time in here one way or another, because we already use HdrHistogram_Py in production, so now I need to fix #13 one way or another (either by fixing `BigEndianStructure` in PyPy, removing it here, or stripping out ctypes entirely)

Seeing the old pure-python code will definitely help I think -- hopefully V1 and V2 are close enough to each other that it's not all wasted code?

**Comment by ahothan** [comment]
Fix PyPy would be fantastic ;-)

**Comment by ahothan** [comment]
Closing this as there is no more immediate need.
