### ISSUE TITLE
Ability to create html files via the Python Histogram API

### ISSUE THREAD

**Issue by kannanekanath** [HdrHistogram/HdrHistogram_py#16]
Hello,
In the past I used the https://github.com/HdrHistogram/HdrHistogram/blob/master/GoogleChartsExample/index.html to create pretty html charts from the histograms. 

The Google chart example requires the input file be in a particular format https://github.com/HdrHistogram/HdrHistogram/blob/master/GoogleChartsExample/example1.txt

The Java API nicely generates with the write methods however I am not able to locate an equivalent Python API. Please could you consider adding this?

I am happy to code up/test/feedback/contribute if necessary

**Comment by ahothan** [comment]
There is actually a method available to do just that:
output_percentile_distribution()
https://github.com/HdrHistogram/HdrHistogram_py/blob/master/hdrh/histogram.py#L576

Perhaps this needs proper documentation?

**Comment by kannanekanath** [comment]
Indeed. I was searching for something along the lines of print but you are right this does need proper documentation

**Comment by kannanekanath** [comment]
I raised https://github.com/HdrHistogram/HdrHistogram_py/pull/17 I will raise another PR after I add the examples.

**Comment by ahothan** [comment]
fixed by https://github.com/HdrHistogram/HdrHistogram_py/commit/48241e28c8aa7aea7ab139b4dec4540dc1a97e24
