### ISSUE TITLE
Unittests fail on 32-bit systems

### ISSUE THREAD

**Issue by dmand** [HdrHistogram/HdrHistogram_py#20]
While working on #19 I've uncovered a few test failures which should probably be addressed.

For example, on 32-bit systems, [`test_basic`](https://github.com/HdrHistogram/HdrHistogram_py/blob/17114a6783c121bc84b12812bbb39351195e7b36/test/test_hdrhistogram.py#L58) fails with `AssertionError: 21 != 22`. This is due to [`get_bucket_count()`](https://github.com/HdrHistogram/HdrHistogram_py/blob/17114a6783c121bc84b12812bbb39351195e7b36/hdrh/histogram.py#L34) using `sys.maxsize` to calculate bucket count, which makes it return `22` on 64-bit platforms and `21` on 32-bit based ones. Not sure yet if it's calculation bug or `sys.maxsize` should be replaced with something else in the calculation (can you clarify?).

On the same 32-bit system `test_hdr_payload` just crashes pytest. No idea about how this happens yet.

I also get the impression that the project would benefit from having a CI set up: Appveyor for regularly running Windows tests, TravisCI for doing the same on Linux/Mac. I can provide some help with setting this up, if you're interested.

**Comment by ahothan** [comment]
Thanks for checking this.
I don't have a windows system so can't easily debug the crash. Can you check for which counter size(s) it is crashing? Please run with each size one time and let me know which crash - do you have a stack trace?

def test_hdr_payload():
    # Check the payload work in all 3 supported counter sizes
    for counter_size in [2, 4, 8]:
        check_hdr_payload(counter_size)

Regarding the CI, this is something that is needed but never got time to implement, so any help there will be great!

**Comment by dmand** [comment]
I'll do some more investigation into failing test cases in a separate pull request.

I'll also see what i can do about setting up CI for the project.

**Comment by dmand** [comment]
So, my fix for `test_basic` is available in #21 .

Looking into `check_hdr_payload` on a 32-bit system was a bit trickier. I was able to ensure only the following statements:
1. `check_hdr_payload(counter_size)` fails  on each value from `[2, 4, 8]`
2. The fail occurs somewhere in `python-codec.c` in `py_hdr_decode` function.

I wasn't able to trace the C code more deeply (at least yet), but it's an old windows's "Access violation" kind of crash. Because the crash occurs in C extension of Python — there is no stacktrace.

**Comment by ahothan** [comment]
this will require debugging the C code on windows server which I do not have.
good news is it seems to be easy to reproduce.
I suspect it might be related to field alignment in struct.
Can you use this library in 64-bit mode on Windows or do you have to stick with 32-bit? Do you need to use a 32-bit windows system?

**Comment by dmand** [comment]
Nope, it's not a requirement to use 32-bits. The project should declare that it doesn't support win32 then, but it's a minor thing.

Closing the issue.
